services:
  api:
    image: projectalchemy.web
    build:
      context: .
      dockerfile: ProjectAlchemy.Web/Dockerfile
    ports:
      - "3000:8080"

  test:
    image: projectalchemy.coretests
    build:
      context: .
      dockerfile: ProjectAlchemy.CoreTests/Dockerfile
    command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput="result.lcov"
    volumes:
      - .:/coverage
