services:
  api:
    image: projectalchemy.web
    build:
      context: .
      dockerfile: ProjectAlchemy.Web/Dockerfile

  test:
    image: projectalchemy.coretests
    build:
      context: .
      dockerfile: ProjectAlchemy.CoreTests/Dockerfile
    command: dotnet test
