name: Deploy

on:
  workflow_dispatch:
  
jobs:
  deploy:
      runs-on: self-hosted
      steps:
        - name: checkout repository
          uses: actions/checkout@v2.1.0

        - name: setup
          run: |
            cd ProjectAlchemy.Web
            echo $APPSETTINGS_BASE64 | base64 -d > appsettings.json
          env:
            APPSETTINGS_BASE64: ${{secrets.APPSETTINGS_JSON_BASE64}}

        - name: Deploy app
          run: make prod

        - name: Check startup health
          run: | 
            sleep 3
            chmod +x ./check_startup_health.sh
            ./check_startup_health.sh
