name: Deploy

on:
  workflow_dispatch:
  
jobs:
  deploy:
      runs-on: self-hosted
      steps:
        - name: checkout repository
          uses: actions/checkout@v2.1.0

        - name: setup
          run: echo '$APPSETTINGS_JSON' > ProjectAlchemy.Web/appsettings.json
          env:
            APPSETTINGS_JSON: ${{secrets.APPSETTINGS.JSON}}

        - name: Deploy app
          run: make prod

        - name: Check startup health
          run: | 
            sleep 1
            chmod +x ./check_startup_health.sh
            ./check_startup_health.sh
