name: Deploy

on:
  workflow_dispatch:
  
jobs:
  deploy:
      runs-on: self-hosted
      steps:
        - name: checkout repository
          uses: actions/checkout@v2.1.0

        - name: Deploy app
          run: make prod
