name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  test:
      runs-on: self-hosted
      steps:
        - name: checkout repository
          uses: actions/checkout@v2.1.0

        - name: Unit Testing
          run: make test
        
        - name: Get Coverage
          run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
          env:
            CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
          
